name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.4.18"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Check formatting with black
      run: uv run black --check .

    - name: Check import sorting with isort
      run: uv run isort --check-only .

    - name: Run tests
      run: uv run pytest tests/ -v

    - name: Test examples
      run: uv run python examples/streetlights_example.py

    - name: Type check (advisory)
      run: uv run mypy asyncapi_pydantics/
      continue-on-error: true
